version: "3.1"

services:

  redis:
    image: "redis:latest"
    command: "redis-server --requirepass ${REDIS_PASS}"
    ports:
      - 6379:6379
  flower:
    image: "mher/flower:latest"
    command: "celery flower --enable_events=False"
    environment:
      CELERY_BROKER_URL: "redis://:${REDIS_PASS}@redis:6379/2"
      FLOWER_URL_PREFIX: flower
      FLOWER_BASIC_AUTH: "${FLOWER_USER}:${FLOWER_PASS}"
    ports:
      - 5555:5555
    volumes:
      - ${FLOWER_DIR}:/data

networks:
  default:
# vim: set sw=2 ts=2 sts=2:
